### ISSUE TITLE
Button to go to next item in the feed?

### ISSUE THREAD

**Issue by EvansJahja** [stijnsanders/feeder#2]
Hiya, I'm enjoying feeder as it is simple to use. I'm mostly using Feeder to look at comics, so I mainly look at image. After I'm done with the current item, I would love a way to go to the next item *without* having to press back, and find the next thing to see.

So here's my expectation:
1. View an item
2.a. Swipe right / left to go to previous / next item
2.b There should be a button on that screen to allow me to go to the next item

I'd love to help but I don't understand Pascal, or how to even compile it :(

Would appreciate if this can be worked out :D

**Comment by stijnsanders** [comment]
Woohoo! A real live user! I currently don't know how to catch a 'swipe event' in client script, so I've added an arrow-right button to open the next post item. (And changed the "open new tab" button to an up-arrow.) Let me know if it performs like you expected.

**Comment by EvansJahja** [comment]
@stijnsanders thank you very much. That should help. However I don't know how to test it. Is it updated on f droid?

**Comment by stijnsanders** [comment]
f-droid? this is not the repository of an android app, you may have posted an issue on the wrong repository

**Comment by EvansJahja** [comment]
> f-droid? this is not the repository of an android app, you may have posted an issue on the wrong repository

Dang it, I'm so so sorry. I've mistaken your repo for gitlab.com/spacecowboy/Feeder which is also an RSS reader. Sorry about that.

**Comment by stijnsanders** [comment]
No problem. I use my rss reader with Firefox on Android
